### ISSUE TITLE
any idea how to fix sentence tokenizer mismatch?

### ISSUE THREAD

**Issue by edchengg** [nlpcl-lab/ace2005-preprocessing#10]
Thanks a lot for your code!

I was trying to use your code for event extraction processing in Chinese and Arabic. It seems to me for Chinese and some Arabic data, the number of sentence tokenizer mismatch is huge. So I end up only get a few sentences from the Chinese corpus.

Do you have any ideas how could we fix that? I tried to replace the nltk.sent_tokenize with my own way to split sentence but the assertion in function find_token_index() stopped the code. I am not sure how to deal with it.

**Comment by spookyQubit** [comment]
Hi @edchengg, I am also trying to use this repo to parse Arabic ACE data. Have you been able make this repo work (or any other open source repo) to get meaningful data for either Chinese or Arabic? Any leads is highly appreciated. Thanks is advance.
