### ISSUE TITLE
Is replace() necessary ?

### ISSUE THREAD

**Issue by sunilitggu** [nlpcl-lab/ace2005-preprocessing#2]
Hi there, 
Thanks for the code.
I found a small mistake in the code, wanna clarify that. In _parse_sgm(sgm_path)_ function, line no https://github.com/nlpcl-lab/ace2005-preprocessing/blob/0c79b123916cb36cf917cb06355551166534a0b4/parser.py#L94
you change the sentence with replace() fun (e.g. 'U.S.' to  'US'). This will change the sentence, therefore when you call find () in line https://github.com/nlpcl-lab/ace2005-preprocessing/blob/0c79b123916cb36cf917cb06355551166534a0b4/parser.py#L125
this will not return the correct position of the sentence in the actual text and will return -1. This lead to the wrong entity set for the sentences.

**Comment by jy007** [comment]
> Hi there,
> Thanks for the code.
> I found a small mistake in the code, wanna clarify that. In _parse_sgm(sgm_path)_ function, line no
> 
> https://github.com/nlpcl-lab/ace2005-preprocessing/blob/0c79b123916cb36cf917cb06355551166534a0b4/parser.py#L94
> 
> 
> you change the sentence with replace() fun (e.g. 'U.S.' to 'US'). This will change the sentence, therefore when you call find () in line
> https://github.com/nlpcl-lab/ace2005-preprocessing/blob/0c79b123916cb36cf917cb06355551166534a0b4/parser.py#L125
> 
> 
> this will not return the correct position of the sentence in the actual text and will return -1. This lead to the wrong entity set for the sentences.

found the same issue, good jod! Thank you for pointing out !  Should replace the words after find pos.

**Comment by jy007** [comment]
> Hi there,
> Thanks for the code.
> I found a small mistake in the code, wanna clarify that. In _parse_sgm(sgm_path)_ function, line no
> 
> https://github.com/nlpcl-lab/ace2005-preprocessing/blob/0c79b123916cb36cf917cb06355551166534a0b4/parser.py#L94
> 
> 
> you change the sentence with replace() fun (e.g. 'U.S.' to 'US'). This will change the sentence, therefore when you call find () in line
> https://github.com/nlpcl-lab/ace2005-preprocessing/blob/0c79b123916cb36cf917cb06355551166534a0b4/parser.py#L125
> 
> 
> this will not return the correct position of the sentence in the actual text and will return -1. This lead to the wrong entity set for the sentences.

found the same issue, good jod! Thank you for pointing out ! Can i change the sgm_text with converted_text ? Or should i replace those word after find pos?

**Comment by bowbowbow** [comment]
@sunilitggu 
Thank you for your detailed explanation.

There were cases in which `nltk.sent_tokenize()` incorrectly splits sentences containing dots, such as "Ltd." and "U.S." To avoid the problem, I used `replace()` to remove this dots.

But I knew there were position problems when using `replace()`.
I removed the `replace()` from the code.

Thank you!
