### ISSUE TITLE
bug in dev.json named entity

### ISSUE THREAD

**Issue by edchengg** [nlpcl-lab/ace2005-preprocessing#3]
Hi, 
thanks for your code!
I found the 'golden-entity-mentions' in dev.json are a little bit strange. 
Most of them are empty or  time '2003-03-29T16:00:00-05:00'.

train and test seems fine to me. Do you encounter similar results? Thank you.

**Comment by shiqing1234** [comment]
> Hi,
> thanks for your code!
> I found the 'golden-entity-mentions' in dev.json are a little bit strange.
> Most of them are empty or time '2003-03-29T16:00:00-05:00'.
> 
> train and test seems fine to me. Do you encounter similar results? Thank you.

i encounter similar result,and can you tell me how do you resolve it?

**Comment by edchengg** [comment]
I write processing code for my case after figuring out how to locate the entity name.

**Comment by bowbowbow** [comment]
@edchengg @shiqing1234 
I checked the generated dev.json and couldn't find the bugs.

What version of the ACE 2005 are you using?
I used a `ace_2005_td_v7_LDC2006T06.tgz` from [LDC2006T06](https://catalog.ldc.upenn.edu/LDC2006T06).

**Comment by marcqleonard** [comment]
I am using `ace_2005_td_v7_LDC2006T06` too and am having the same problem. The `golden-entity-mentions` are either empty or contain the following:

```python
    "golden-entity-mentions": [
      {
        "text": "2003-03-29T16:00:00-05:00",
        "entity-type": "TIM:time",
        "start": 8,
        "end": 9
      }
```

The few that contain mentions do not seem to match the sentence they are supposed to match, e.g.:

```python
"sentence": "Iraqis who initially were cautious when US forces arrived in Najaf ended cheering them on, shaking their hands and patting their backs.",
    "golden-entity-mentions": [
      {
        "text": "WOLF BLITZER",
        "entity-type": "PER:Individual",
        "start": 20,
        "end": 22
      },
      {
        "text": "2003-04-02T16:00:00-05:00",
        "entity-type": "TIM:time",
        "start": 5,
        "end": 6
      }
    ],
```

**Comment by bowbowbow** [comment]
@marcqleonard 
Thank you for your detailed explanation.

The problem seems to have been solved through a commit I made a while ago.
My dev.json has no problem with the example you shared as shown in below.
```
"sentence": "Iraqis who initially were cautious when U.S. forces arrived in Najaf ended cheering them on, shaking their hands and patting their backs.",
"golden-entity-mentions": [
      {
        "text": "Najaf",
        "entity-type": "GPE:Population-Center",
        "start": 10,
        "end": 11
      },
      {
        "text": "Iraqis who initially were cautious when U.S. forces arrived in Najaf",
        "entity-type": "PER:Group",
        "start": 0,
        "end": 11
      },
      {
        "text": "who",
        "entity-type": "PER:Group",
        "start": 1,
        "end": 2
      },
      {
        "text": "U.S. forces",
        "entity-type": "PER:Group",
        "start": 6,
        "end": 8
      },
      {
        "text": "them",
        "entity-type": "PER:Group",
        "start": 13,
        "end": 14
      },
      {
        "text": "their",
        "entity-type": "PER:Group",
        "start": 17,
        "end": 18
      },
      {
        "text": "their",
        "entity-type": "PER:Group",
        "start": 21,
        "end": 22
      },
      {
        "text": "U.S",
        "entity-type": "GPE:Nation",
        "start": 6,
        "end": 7
      }
],
```

Can you run the pre-processing again to see if the problem is resolved?

**Comment by marcqleonard** [comment]
@bowbowbow - I just re-run the latest version of the script up to commit `6f057397c2e5b5f2434cb06030326a50bedb641f` (`update statistics of preprocessed result`). The issue I was having is fixed.

Thanks!
