### ISSUE TITLE
fail to find offset! start_index: 3348, text: Doctors Without Borders/Médecins Sans Frontières

### ISSUE THREAD

**Issue by SilenceWinter** [nlpcl-lab/ace2005-preprocessing#6]
Thanks for your sharing！ When running this code and in the step of “preprocessing('train', train_files)” ， I encount the error as below:

71%|███████▏  | 377/529
Traceback (most recent call last):
  File "E:/githubspace/ace2005-preprocessing/main.py", line 213, in <module>
    preprocessing('train', train_files)
  File "E:/githubspace/ace2005-preprocessing/main.py", line 143, in preprocessing
    phrase=entity_mention['text'],
  File "E:/githubspace/ace2005-preprocessing/main.py", line 49, in find_token_index
    assert end_idx != -1, "end_idx: {}, end_pos: {}, phrase: {}, tokens: {}, chars:{}".format(end_idx, end_pos, phrase, tokens, chars)
AssertionError: end_idx: -1, end_pos: 133, phrase: Doctors Without Borders/Médecins Sans Frontières (MSF, tokens: [{'index': 1, 'word': '``', 'originalText': '"', 'lemma': '``', 'characterOffsetBegin': 0, 'characterOffsetEnd': 1, 'pos': '``', 'before': '', 'after': ''}, {'index': 2, 'word': 'Doctors', 'originalText': 'Doctors', 'lemma': 'doctor', 'characterOffsetBegin': 1, 'characterOffsetEnd': 8, 'pos': 'NNS', 'before': '', 'after': ' '}, {'index': 3, 'word': 'Without', 'originalText': 'Without', 'lemma': 'without', 'characterOffsetBegin': 9, 'characterOffsetEnd': 16, 'pos': 'IN', 'before': ' ', 'after': ' '}, {'index': 4, 'word': 'Borders/M茅decins', 'originalText': 'Borders/M茅decins', 'lemma': 'borders/m茅decins', 'characterOffsetBegin': 17, 'characterOffsetEnd': 33, 'pos': 'NNS', 'before': ' ', 'after': ' '}, {'index': 5, 'word': 'Sans', 'originalText': 'Sans', 'lemma': 'san', 'characterOffsetBegin': 34, 'characterOffsetEnd': 38, 'pos': 'VBZ', 'before': ' ', 'after': ' '}, {'index': 6, 'word': 'Fronti猫res', 'originalText': 'Fronti猫res', 'lemma': 'fronti猫res', 'characterOffsetBegin': 39, 'characterOffsetEnd': 49, 'pos': 'NNS', 'before': ' ', 'after': ' '}, {'index': 7, 'word': '-LRB-', 'originalText': '(', 'lemma': '-lrb-', 'characterOffsetBegin': 50, 'characterOffsetEnd': 51, 'pos': '-LRB-', 'before': ' ', 'after': ''}, {'index': 8, 'word': 'MSF', 'originalText': 'MSF', 'lemma': 'msf', 'characterOffsetBegin': 51, 'characterOffsetEnd': 54, 'pos': 'NN', 'before': '', 'after': ''}, {'index': 9, 'word': '-RRB-', 'originalText': ')', 'lemma': '-rrb-', 'characterOffsetBegin': 54, 'characterOffsetEnd': 55, 'pos': '-RRB-', 'before': '', 'after': ' '}, {'index': 10, 'word': 'has', 'originalText': 'has', 'lemma': 'have', 'characterOffsetBegin': 56, 'characterOffsetEnd': 59, 'pos': 'VBZ', 'before': ' ', 'after': ' '}, {'index': 11, 'word': 'received', 'originalText': 'received', 'lemma': 'receive', 'characterOffsetBegin': 60, 'characterOffsetEnd': 68, 'pos': 'VBN', 'before': ' ', 'after': ' '}, {'index': 12, 'word': 'an', 'originalText': 'an', 'lemma': 'a', 'characterOffsetBegin': 69, 'characterOffsetEnd': 71, 'pos': 'DT', 'before': ' ', 'after': ' '}, {'index': 13, 'word': 'extraordinary', 'originalText': 'extraordinary', 'lemma': 'extraordinary', 'characterOffsetBegin': 72, 'characterOffsetEnd': 85, 'pos': 'JJ', 'before': ' ', 'after': ' '}, {'index': 14, 'word': 'outpouring', 'originalText': 'outpouring', 'lemma': 'outpouring', 'characterOffsetBegin': 86, 'characterOffsetEnd': 96, 'pos': 'NN', 'before': ' ', 'after': ' '}, {'index': 15, 'word': 'of', 'originalText': 'of', 'lemma': 'of', 'characterOffsetBegin': 97, 'characterOffsetEnd': 99, 'pos': 'IN', 'before': ' ', 'after': ' '}, {'index': 16, 'word': 'support', 'originalText': 'support', 'lemma': 'support', 'characterOffsetBegin': 100, 'characterOffsetEnd': 107, 'pos': 'NN', 'before': ' ', 'after': ' '}, {'index': 17, 'word': 'for', 'originalText': 'for', 'lemma': 'for', 'characterOffsetBegin': 108, 'characterOffsetEnd': 111, 'pos': 'IN', 'before': ' ', 'after': ' '}, {'index': 18, 'word': 'the', 'originalText': 'the', 'lemma': 'the', 'characterOffsetBegin': 112, 'characterOffsetEnd': 115, 'pos': 'DT', 'before': ' ', 'after': ' '}, {'index': 19, 'word': 'people', 'originalText': 'people', 'lemma': 'people', 'characterOffsetBegin': 116, 'characterOffsetEnd': 122, 'pos': 'NNS', 'before': ' ', 'after': ' '}, {'index': 20, 'word': 'of', 'originalText': 'of', 'lemma': 'of', 'characterOffsetBegin': 123, 'characterOffsetEnd': 125, 'pos': 'IN', 'before': ' ', 'after': ' '}, {'index': 21, 'word': 'South', 'originalText': 'South', 'lemma': 'South', 'characterOffsetBegin': 126, 'characterOffsetEnd': 131, 'pos': 'NNP', 'before': ' ', 'after': ' '}, {'index': 22, 'word': 'Asia', 'originalText': 'Asia', 'lemma': 'Asia', 'characterOffsetBegin': 132, 'characterOffsetEnd': 136, 'pos': 'NNP', 'before': ' ', 'after': ' '}, {'index': 23, 'word': 'and', 'originalText': 'and', 'lemma': 'and', 'characterOffsetBegin': 137, 'characterOffsetEnd': 140, 'pos': 'CC', 'before': ' ', 'after': ' '}, {'index': 24, 'word': 'we', 'originalText': 'we', 'lemma': 'we', 'characterOffsetBegin': 141, 'characterOffsetEnd': 143, 'pos': 'PRP', 'before': ' ', 'after': ' '}, {'index': 25, 'word': 'are', 'originalText': 'are', 'lemma': 'be', 'characterOffsetBegin': 144, 'characterOffsetEnd': 147, 'pos': 'VBP', 'before': ' ', 'after': ' '}, {'index': 26, 'word': 'extremely', 'originalText': 'extremely', 'lemma': 'extremely', 'characterOffsetBegin': 148, 'characterOffsetEnd': 157, 'pos': 'RB', 'before': ' ', 'after': ' '}, {'index': 27, 'word': 'grateful', 'originalText': 'grateful', 'lemma': 'grateful', 'characterOffsetBegin': 158, 'characterOffsetEnd': 166, 'pos': 'JJ', 'before': ' ', 'after': ''}, {'index': 28, 'word': '.', 'originalText': '.', 'lemma': '.', 'characterOffsetBegin': 166, 'characterOffsetEnd': 167, 'pos': '.', 'before': '', 'after': ''}], chars:extraordinaryoutpouringofsupportforthepeopleofSouthAsiaandweareextremelygrateful
Exception ignored in: <bound method tqdm.__del__ of  71%|███████▏  | 377/529 [13:06<11:34,  4.57s/it]>
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\lib\site-packages\tqdm\_tqdm.py", line 931, in __del__
    self.close()
  File "D:\ProgramData\Anaconda3\lib\site-packages\tqdm\_tqdm.py", line 1133, in close
    self._decr_instances(self)
  File "D:\ProgramData\Anaconda3\lib\site-packages\tqdm\_tqdm.py", line 496, in _decr_instances
    cls.monitor.exit()
  File "D:\ProgramData\Anaconda3\lib\site-packages\tqdm\_monitor.py", line 52, in exit
    self.join()
  File "D:\ProgramData\Anaconda3\lib\threading.py", line 1053, in join
    raise RuntimeError("cannot join current thread")
RuntimeError: cannot join current thread

**Comment by bowbowbow** [comment]
@SilenceWinter

Thank you for sharing the details of the error.

Can you check the two things below?

1. What version of the **ACE 2005** did you use?
I used a `ace_2005_td_v7_LDC2006T06.tgz` from [LDC2006T06](https://catalog.ldc.upenn.edu/LDC2006T06).

2. Is this the last version of commit ([db784f18d0382cfe5842f0f14d2b6d12d0d756b2](https://github.com/nlpcl-lab/ace2005-preprocessing/commit/db784f18d0382cfe5842f0f14d2b6d12d0d756b2))?

**Comment by SilenceWinter** [comment]
@bowbowbow  
1.  My version is ace_2005_td_v7_LDC2006T06-EDR .
2.  Yes, it is the last version.

Now  I have solved the problem by deleting the relative error files "alt.vacation.las-vegas_20050109"

**Comment by bowbowbow** [comment]
@SilenceWinter

Is it okay if the files were deleted? If it's the problem with the code, not the files, I'll try to solve it by testing it on ` alt.vacation.las-vegas_20050109`.

**Comment by SilenceWinter** [comment]
@bowbowbow  After deleting the files， the code could run ok.

**Comment by chmod-700** [comment]
What's wrong with the 'alt.vacation.las-vegas_20050109'?
I found that the code could run properly keeping the las-vegas data by commenting out the assertion code.
But I don't know whether there will be any problem with that.
