### ISSUE TITLE
Some entities, event triggers and arguments not in sentence

### ISSUE THREAD

**Issue by marcqleonard** [nlpcl-lab/ace2005-preprocessing#7]
Hi there,

We have found that some of samples in the output have entities, event triggers and event arguments that do not appear in their sentence.

We made a test script to detect problematic samples and describe each inconsistency:
- https://github.com/marcqleonard/ace2005-preprocessing/commits/bugfix-offbyone

Results of our test is that:
- 187 samples in the train.json set have at least one entity or a trigger or an argument that does not appear in their sentence
- 2 samples in test.json
- 5 samples in dev.json

What seems to be happening is that some samples end up with no entity or event trigger or event arguments as they end up being in the next sample.

:(

**Comment by marcqleonard** [comment]
Ooooooops, we were not actually using the latest version. 😑😑😑

[3eee0b6a3ff8093227c3a32e67a64c8584dcc7d3](https://github.com/nlpcl-lab/ace2005-preprocessing/commit/3eee0b6a3ff8093227c3a32e67a64c8584dcc7d3) seems to have fixed it.

**Comment by bowbowbow** [comment]
@marcqleonard 

Thanks for your interest in this work.
I'm glad it's worked out.

I want to solve all the errors of the preprocessing clearly.
Let me know if you find another problem.

Your help is much appreciated.
