### ISSUE TITLE
output

### ISSUE THREAD

**Issue by 787205128** [nlpcl-lab/ace2005-preprocessing#8]
zhou@zhou-Lenovo-Legion-Y7000P-1060:~/文档/ace2005-preprocessing-master$ sudo python main.py --data =/home/zhou/文档/ACE/English/
====================
('[preprocessing] type: ', 'dev')
0it [00:00, ?it/s]
======[Statistics]======
('sent :', 0)
('event :', 0)
('entity :', 0)
('argument:', 0)
Complete verification
====================
('[preprocessing] type: ', 'test')
0it [00:00, ?it/s]
======[Statistics]======
('sent :', 0)
('event :', 0)
('entity :', 0)
('argument:', 0)
Complete verification
====================
('[preprocessing] type: ', 'train')
0it [00:00, ?it/s]
======[Statistics]======
('sent :', 0)
('event :', 0)
('entity :', 0)
('argument:', 0)
Complete verification

**Comment by WAPING** [comment]
环境没有配置好

**Comment by bowbowbow** [comment]
@787205128 @WAPING 

What version of the ACE 2005 are you using?
I used a ace_2005_td_v7_LDC2006T06.tgz from [LDC2006T06](https://catalog.ldc.upenn.edu/LDC2006T06).

Do you have the same directory structure as shown in the bellow.
<img src="https://user-images.githubusercontent.com/13119112/67372275-9d199d80-f5b8-11e9-9799-915dee84be2d.jpg" width="400px"/>

**Comment by WAPING** [comment]
> @787205128 @WAPING
> 
> What version of the ACE 2005 are you using?
> I used a ace_2005_td_v7_LDC2006T06.tgz from [LDC2006T06](https://catalog.ldc.upenn.edu/LDC2006T06).
> 
> Do you have the same directory structure as shown in the bellow.
> <img alt="" width="400px" src="https://user-images.githubusercontent.com/13119112/67372275-9d199d80-f5b8-11e9-9799-915dee84be2d.jpg">

same with you used

**Comment by bowbowbow** [comment]
@WAPING 

I just tried on the latest commit version and it works well.
```
[preprocessing] type:  dev
======[Statistics]======
sent : 875
event : 505
entity : 4050
argument: 933
Complete verification

[preprocessing] type:  test
======[Statistics]======
sent : 713
event : 424
entity : 4226
argument: 892
Complete verification
====================

...
```

Could you show me console logs after adding `print('dev_files :', dev_files)` in main.py?

```python
if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--data', help="Path of ACE2005 English data", default='./data/ace_2005_td_v7/data/English')
    args = parser.parse_args()
    test_files, dev_files, train_files = get_data_paths(args.data)
    print('test_files :', test_files) ## This line
```

**Comment by WAPING** [comment]
Ok， it is
runing

发送自 Windows 10 版邮件应用

发件人: bowbowbow
发送时间: 2019年10月23日 17:02
收件人: nlpcl-lab/ace2005-preprocessing
抄送: Wang anping; Mention
主题: Re: [nlpcl-lab/ace2005-preprocessing] output (#8)

@WAPING
I just tried on the latest commit version and it works well.
[preprocessing] type:  dev
======[Statistics]======
sent : 875
event : 505
entity : 4050
argument: 933
Complete verification

[preprocessing] type:  test
======[Statistics]======
sent : 713
event : 424
entity : 4226
argument: 892
Complete verification
====================

...
Could you show me console logs after adding print('dev_files :', dev_files) in main.py?
if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--data', help="Path of ACE2005 English data", default='./data/ace_2005_td_v7/data/English')
    args = parser.parse_args()
    test_files, dev_files, train_files = get_data_paths(args.data)
    print('test_files :', test_files) ## This line

**Comment by WAPING** [comment]
[preprocessing] type:  dev
======[Statistics]======
sent : 875
event : 505
entity : 4050
argument: 933
Complete verification
====================
[preprocessing] type:  test
======[Statistics]======
sent : 713
event : 424
entity : 4226
argument: 892
Complete verification
====================
[preprocessing] type:  train
======[Statistics]======
sent : 14724
event : 4420
entity : 53045
argument: 7811
Complete verification

Just like this，

print('dev_files :', dev_files) in main.py
this function is just to get the dev file list in the data_list


发送自 Windows 10 版邮件应用

发件人: bowbowbow
发送时间: 2019年10月23日 17:02
收件人: nlpcl-lab/ace2005-preprocessing
抄送: Wang anping; Mention
主题: Re: [nlpcl-lab/ace2005-preprocessing] output (#8)

@WAPING
I just tried on the latest commit version and it works well.
[preprocessing] type:  dev
======[Statistics]======
sent : 875
event : 505
entity : 4050
argument: 933
Complete verification

[preprocessing] type:  test
======[Statistics]======
sent : 713
event : 424
entity : 4226
argument: 892
Complete verification
====================

...
Could you show me console logs after adding print('dev_files :', dev_files) in main.py?
if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--data', help="Path of ACE2005 English data", default='./data/ace_2005_td_v7/data/English')
    args = parser.parse_args()
    test_files, dev_files, train_files = get_data_paths(args.data)
    print('test_files :', test_files) ## This line

**Comment by bowbowbow** [comment]
@WAPING It seems to work well on your environment.

@787205128 How about you?
